### ISSUE TITLE
Problem installing from backend

### ISSUE THREAD

**Issue by inalto** [albrightlabs/nofrontend-plugin#2]
When i try to install it from the backend it gives this error, maybe is related to the fact that no v1.0 version was set as release on github? Or maybe you have to register it on packagist.org (not sure)?

![immagine](https://user-images.githubusercontent.com/6382732/199705290-573cb92d-cf5e-49b6-84dd-883afb3d2e10.png)

octobercms 3.1.21

**Comment by joebuonocore** [comment]
An updated version of the plugin has been released (v1.0.3) and you should be able to install it via the backend or command line. If you continue to have trouble please contact again!
